version: '3'
services:
  mongo:
    image: mongo:3.4.6
    container_name: fue-mongo
    ports:
      - "27017:27017"
    volumes:
      - ~/docker/mongodb/log:/var/log/mongodb
      - ~/docker/data/db:/data/db

